---
title: "Team Names Unification"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical: scroll
runtime: shiny
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = TRUE)

library(flexdashboard)
library(tidyverse)
library(pool)
library(dbplyr)
library(DBI)
library(config)
library(GetoptLong)
library(logging)
library(lubridate)
library(data.table)
library(dplyr)
library(DT)
library(stringr)
library(xlsx)

# ---- Enable to upload a bit bigger files -----
options(shiny.maxRequestSize = 30 * 1024 ^ 2)
options(java.parameters = "-Xmx12G")

# ----- load ETL Data -----
load(paste(get("working_directory")[["4finance_PC"]], "/", 
           get("data_location")$results_data, sep = ""))

load(paste(get("working_directory")[["4finance_PC"]], "/", 
           get("data_location")$tipsport_data, sep = ""))
```

```{r Establish Editing, eval = T, include = T, comment = F, echo = F}
modDtUi <- function(id){
  ns = NS(id)
  DT::dataTableOutput(ns('x1'))
}

modDt <-  function(input, output, session, data){
  output$x1 <- 
    DT::renderDataTable(data, 
                        selection = "none", 
                        editable = list(target = "cell",
                                        disable = 
                                          list(columns = 
                                                 c(1, 2))), 
                        server = TRUE, 
                        options = list(scrollY = "400px", 
                                       paging = T,
                                       pageLength = 5,
                                       scrollX = TRUE, 
                                       searchHighlight = TRUE,
                                       fixedColumns = list(leftColumns = 2)), 
                        filter = "top", class = "cell-border stripe") 
  proxy <- dataTableProxy("x1", session = session)
  
  updatedData <- eventReactive(input$x1_cell_edit, {
    info = input$x1_cell_edit
    if (!is.null(info)) {
      str(info)
      data[info$row, info$col] <<- DT::coerceValue(info$value,
                                                   data[info$row, info$col])
    }
    data
  }, ignoreNULL = FALSE)
  
  return(updatedData)
}
```

```{r Sorting League Names, eval = T, include = T, comment = F, echo = F}
get_files <- 
  list.files(paste(get("working_directory")[["4finance_PC"]], "/", 
                   get("data_location")$league_mapping, sep = ""))
if("league_mapping.RData" %in% get_files){
  load(paste(get("working_directory")[["4finance_PC"]], "/", 
             get("data_location")$league_mapping, 
             "/league_mapping.RData", sep = ""))
  
  league_data <- league_mapping
}else{
  league_data <- 
    data.frame("Results" = get("league_mapping")$results_data,
               "Tipsport" = get("league_mapping")$tipsport_data,
               "Tipsport_Changed" = get("league_mapping")$tipsport_data) %>%
    mutate_if(., is.factor, as.character)
}
```

Row {data-height=700}
-----------------------------------------------------------------------

### League Dictionary
```{r Editable League Names, eval = T, include = T, comment = F, echo = F}
modDtUi("editable_league")
changed_league <- callModule(modDt, "editable_league", data = league_data)
```

```{r Save Leage Changes, eval = T, include = T, comment = F, echo = F}
# ----- Save Changes -----
saved_changes <- reactive({
  upload_temp <- changed_league() %>% as.data.frame()
  
  return(upload_temp)
})
```

```{r Saving League Mapping, eval = T, include = T, comment = F, echo = F}
# ----- Save Button -----
actionButton("upload_data", h4("Store League Mapping"))
upload_changes <- eventReactive(input$upload_data, {
  
  league_mapping <- 
    saved_changes() %>% 
    as.data.frame()
  
  save(league_mapping, file = paste(get("league_mapping")$mapping_storage))
})

renderText({
  upload_changes()
})
```

```{r Tipsport Teams, eval = T, include = F, comment = F, echo = F}
tipsport_teams <-
  data_temp %>%
  filter(sport_category %in% "Fotbal - muži" &
           (eventtypedescription %in% c("Vítěz", "Počet gólů (bodů)")) &
           sport_league %in% league_data$Tipsport_Changed & 
           !(type %in% c("x", "o", "u"))) %>%
  rbind(., data_temp %>%
          filter(sport_category %in% "Fotbal - muži" &
                   eventtypedescription %in% c("Vítěz", "Počet gólů (bodů)") &
                   sport_league %in% league_data$Tipsport_Changed & 
                   !(type %in% c("x", "o", "u")))) %>%
  as.data.frame() %>%
  select(fullname, sport_league, dateclosed) %>%
  select(-dateclosed) %>%
  distinct() %>% 
  rename(`Team Name [Tipsport]` = fullname,
         `Tipsport League` = sport_league) %>%
  as.data.frame()
```

```{r Results Teams, eval = T, include = T, comment = F, echo = F}
get_team_files <- 
  list.files(paste(get("working_directory")[["4finance_PC"]], "/", 
                   get("data_location")$league_mapping, sep = ""))
if("team_mapping.RData" %in% get_team_files){
  load(paste(get("working_directory")[["4finance_PC"]], "/", 
             get("data_location")$league_mapping, 
             "/team_mapping.RData", sep = ""))
  
  results_teams <- team_mapping
}else{
  results_teams <- 
    master_data %>%
    select(Div, HomeTeam, AwayTeam) %>%
    distinct() %>%
    gather(is_home, team, HomeTeam, AwayTeam) %>%
    select(-is_home) %>%
    rename(`Results League` = Div,
           `Results Team` = team) %>%
    distinct() %>%
    
    left_join(., league_data %>% as.data.frame(), 
              by = c("Results League" = "Results")) %>%
    
    left_join(., tipsport_teams %>% 
                mutate(`Joined` = 1) %>%
                as.data.frame(), 
              by = c("Tipsport_Changed" = "Tipsport League", 
                     "Results Team" = "Team Name [Tipsport]")) %>%
    
    rowwise() %>%
    mutate(`Tipsport Team [Changed]` = 
             ifelse(is.na(Joined), NA, `Results Team`)) %>%
    mutate(Joined = replace_na(Joined, 0))
}
```

```{r Removals, eval = T, include = F}
rm(data_temp)
gc()

rm(master_data)
gc()
```

Row {data-height=700}
-----------------------------------------------------------------------

### Joined Table
```{r Editable Team Names, eval = T, include = T, comment = F, echo = F}
modDtUi("editable")
changed_team <- callModule(modDt, "editable", data = results_teams)
```

```{r Save Joined Changes, eval = T, include = T, comment = F, echo = F}
# ----- Save Changes -----
saved_team_changes <- reactive({
  upload_team <- changed_team() %>% as.data.frame()
  return(upload_team)
})
```

### Tipsport Teams
```{r Tipsport Helper Table, eval = T, include = T, comment = F, echo = F}
DT::datatable(tipsport_teams %>%
                as.data.frame(), 
              
              options = list(scrollY = "400px", 
                             paging = TRUE,
                             pageLength = 5,
                             scrollX = TRUE, 
                             searchHighlight = TRUE,
                             fixedColumns = list(leftColumns = 2)), 
              filter = "top", class = "cell-border stripe")
```

```{r Saving Team Mapping, eval = T, include = T, comment = F, echo = F}
# ----- Save Button -----
actionButton("upload_team_data", h4("Store Team Mapping"))
upload_team_changes <- eventReactive(input$upload_team_data, {
  
  team_mapping <- 
    saved_team_changes() %>% 
    as.data.frame()
  
  save(team_mapping, file = get("team_mapping")$mapping_storage)
})

renderText({
  upload_team_changes()
})
```
