drop table if exists t_match_stats cascade;

create table if not exists t_match_stats ( season varchar(50) not null,
league varchar(50) not null,
created_at date not null,
ftr varchar(50) not null,
fthg integer not null,
ftag integer not null,
hs integer,
"as" integer,
hst integer,
ast integer,
hf integer,
af integer,
hc integer,
ac integer,
hy integer,
ay integer,
hr integer,
ar integer,
b365h real,
b365d real,
b365a real,
bwh real,
bwd real,
bwa real,
iwh real,
iwd real,
iwa real,
psh real,
psd real,
psa real,
whh real,
whd real,
wha real,
vch real,
vcd real,
vca real,
"b365.2.5" real,
"b365.2.5.1" real,
"p.2.5" real,
"p.2.5.1" real,
"gb.2.5" real,
"gb.2.5.1" real,
match_id integer not null,
is_home integer not null,
team varchar(50) not null);
