---
title: "Data Pinning - Local"
author: "Ing. Peter Tomko, M.A."
date: "29/8/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = F, echo = T}
library(data.table)
library(dplyr)
library(pins)

pins::board_register(board = "local")
```

# Downloading Views

## Connection
```{r connection, warning = F, message = F, error = F}
con <- DBI::dbConnect(odbc::odbc(), "betting_ds", bigint = "integer")
```

## Last Matches
```{sql Last Matches, connection = con, output.var = "v_last_matches"}
select * from v_last_matches;
```

## Match Statistics
```{sql Match Stats, connection = con, output.var = "v_match_stats"}
select * from v_match_stats;
```

## Bookmakers Odds
```{sql Bookmakers Data, connection = con, output.var = "t_match_stats"}
select * from t_match_stats;
```

## Upcoming Matches
```{sql Upcoming Matches, connection = con, output.var = "v_upcoming_matches"}
select distinct created_at, dateclosed, fullname, sport_league, 
trim(BOTH from t_home_team) as t_home_team,
trim(BOTH from t_away_team) as t_away_team,
rate from v_upcoming_matches;
```

## Mapping Table
```{sql Mapping Table, connection = con, output.var = "t_mapping_team"}
select distinct tipsport_league, results_league, results_team, tipsport_team from
(select distinct created_at, tipsport_league, results_league, results_team, tipsport_team, last_update
from 
(select created_at, 
trim(both tipsport_league) as tipsport_league, 
trim(both results_league) as results_league, 
trim(both results_team) as results_team, 
trim(both tipsport_team) as tipsport_team, 
max(created_at) over(partition by tipsport_league, results_league, results_team, tipsport_team) as last_update 
from t_mapping_team) as m_data
where created_at = last_update) actual_mapping;
```

## Target Variable

```{sql Target Variable, connection = con, output.var = "target_vars"}
select distinct season, league, team, match_id, created_at, n_goals 
from v_match_stats;
```

# To Board
```{r Board Pinning, warning = F, message = F, error = T}
v_last_matches %>% pin("v_last_matches", board = "local")
v_match_stats %>% pin("v_match_stats", board = "local")
t_match_stats %>% pin("t_match_stats", board = "local")
v_upcoming_matches %>% pin("v_upcoming_matches", board = "local")
t_mapping_team %>% pin("t_mapping_team", board = "local")
target_vars %>% pin("target_vars", board = "local")
```
