---
title: "Create Mapping Tables"
author: "Ing. Peter Tomko, M.A."
date: "27/8/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = TRUE)
```

NOTE: RUN ONLY AT THE BEGINNING, i.e. when downloading data for the first time.

## Initiate Connection

```{r connection, warning = F, message = F, error = T}
con <- DBI::dbConnect(odbc::odbc(), "betting_ds")
```

## Create `t_mapping_league`
```{sql League, connection = con, warning = F, message = F, error = T}
drop table if exists t_mapping_league;
create table if not exists t_mapping_league (
created_at timestamp without time zone not null,
tipsport_league varchar(50) not null,
results_league varchar(50) not null);
```

## Create `t_mapping_team`
```{sql Team, connection = con, warning = F, message = F, error = T}
drop table if exists t_mapping_team;
create table if not exists t_mapping_team (
created_at timestamp without time zone not null,
results_league varchar(50) not null,
results_team varchar(50) not null,
tipsport_team varchar(50) not null,
tipsport_league varchar(50) not null);
```
