---
title: "Betting DS - app"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical: scroll
runtime: shiny
---

```{r setup, include = F, echo = T}
library("flexdashboard")
library("tidyverse")
library("pool")
library("dbplyr")
library("DBI")
library("config")
library("GetoptLong")
library("logging")
library("lubridate")
library("data.table")
library("dplyr")
library("DT")
library("stringr")
library("xlsx")
library("generalToolboxR")

# ---- Enable to upload a bit bigger files -----
options(shiny.maxRequestSize = 30 * 1024 ^ 2)
options(java.parameters = "-Xmx12G")

# ----- Connect to Database -----
betting_ds <- dbManager$new()
betting_ds$db_config(db_drv = "PostgreSQL",
                     db_name = "betting_ds",
                     host = "localhost",
                     port = 5432,
                     user = "postgres",
                     password = "thatSounds77")

# ----- Download Data Prerequisites -----
v_match_stats <- 
  betting_ds$run(sql_statement = "select distinct trim(both league) as league, trim(both team) as team from v_match_stats;")

t_mapping_league <- 
  betting_ds$run(sql_path = "C:/Users/Peter/Desktop/ds_projects/betting_data_science/db/mapping app scripts/get mapping league.sql")

t_mapping_team <- 
  betting_ds$run(sql_path = "C:/Users/Peter/Desktop/ds_projects/betting_data_science/db/mapping app scripts/get mapping team.sql")

v_tipsport_bookmaker <- 
  betting_ds$run(sql_path = "C:/Users/Peter/Desktop/ds_projects/betting_data_science/db/mapping app scripts/get bookmaker data.sql")
```

```{r Establish League Editing, eval = T, include = T, comment = F, echo = F}
modDtUi <- function(id){
  ns = NS(id)
  DT::dataTableOutput(ns('x1'))
}

modDt <-  function(input, output, session, data){
  output$x1 <- 
    DT::renderDataTable(data, 
                        selection = "none", 
                        editable = list(target = "all",
                                        disable = 
                                          list(columns = 
                                                 c(1))), 
                        server = TRUE, 
                        options = list(scrollY = "400px", 
                                       paging = T,
                                       pageLength = 5,
                                       scrollX = TRUE, 
                                       searchHighlight = F,
                                       fixedColumns = list(leftColumns = 2)), 
                        filter = "top", class = "cell-border stripe") 
  proxy <- dataTableProxy("x1", session = session)
  
  updatedData <- eventReactive(input$x1_cell_edit, {
    info = input$x1_cell_edit
    if (!is.null(info)) {
      str(info)
      data <<- DT::editData(data, info)
    }
    data
  }, ignoreNULL = FALSE)
  
  return(updatedData)
}
```

Row {data-height=700}
-----------------------------------------------------------------------

### League Dictionary
```{r Editable League Names, eval = T, include = T, comment = F, echo = F}
# ----- Initiate Editing -----
modDtUi("editable_league")
changed_league <- 
  callModule(modDt, "editable_league", 
             data = v_match_stats %>%
               dplyr::select(league) %>%
               dplyr::distinct() %>%
               dplyr::rename(`Results League` = league) %>%
               dplyr::left_join(., t_mapping_league, 
                                by = c("Results League" = "results_league")) %>%
               dplyr::rename(`Tipsport League` = tipsport_league) %>%
               as.data.frame())

# ----- Rewrite Table -----
saved_changes <- reactive({
  upload_temp <- changed_league() %>% as.data.frame()
  
  return(upload_temp)
})

# ----- Save to Database -----
actionButton("upload_data", h4("Store League Mapping"))
upload_changes <- eventReactive(input$upload_data, {
  
  league_mapping <- 
    
    saved_changes() %>%
    
    dplyr::mutate(created_at = Sys.time()) %>%
    dplyr::filter(`Tipsport League` != c("")) %>%
    dplyr::rename(tipsport_league = `Tipsport League`,
                  results_league = `Results League`) %>%
    na.omit() %>%
    as.data.frame()
  
  if(nrow(league_mapping) > 0) {
    
    betting_ds$writeTable(df = league_mapping, 
                          table_name = "t_mapping_league", 
                          is_append = T, is_overwrite = F)
    
  }
})

renderText({
  upload_changes()
})
```

### List of Tipsport Leagues

```{r League List, eval = T, include = T, comment = F, echo = F}
DT::datatable(v_tipsport_bookmaker %>%
                # dplyr::filter(sport_category %in% "Fotbal - muži") %>%
                dplyr::select(sport_league) %>%
                dplyr::distinct() %>%
                dplyr::rename(`Tipsport League` = sport_league) %>%
                as.data.frame(), 
              
              options = list(scrollY = "400px", 
                             paging = TRUE,
                             pageLength = 5,
                             scrollX = TRUE, 
                             searchHighlight = F,
                             fixedColumns = list(leftColumns = 2)), 
              filter = "top", class = "cell-border stripe")

```

### Stored Mappings in DB

```{r Actual DB State League, eval = T, include = T, comment = F, echo = F}
DT::datatable(t_mapping_league %>%
                as.data.frame(), 
              
              options = list(scrollY = "400px", 
                             paging = TRUE,
                             pageLength = 5,
                             scrollX = TRUE, 
                             searchHighlight = F,
                             fixedColumns = list(leftColumns = 2)), 
              filter = "top", class = "cell-border stripe")

```


```{r Tipsport Teams, eval = T, include = F, comment = F, echo = F}
tipsport_teams <-
  v_tipsport_bookmaker %>%
  dplyr::filter(sport_category %in% "Fotbal - muži" &
                  (eventtypedescription %in% c("Vítěz", "Počet gólů (bodů)")) &
                  # sport_league %in% t_mapping_league$tipsport_league & 
                  !(type %in% c("x", "o", "u"))) %>%
  rbind(., v_tipsport_bookmaker %>%
          dplyr::filter(sport_category %in% "Fotbal - muži" &
                          eventtypedescription %in% c("Vítěz", "Počet gólů (bodů)") &
                          sport_league %in% t_mapping_league$tipsport_league & 
                          !(type %in% c("x", "o", "u")))) %>%
  as.data.frame() %>%
  dplyr::select(fullname, sport_league, dateclosed) %>%
  dplyr::select(-dateclosed) %>%
  dplyr::distinct() %>% 
  dplyr::rename(`Tipsport Team Name` = fullname,
                `Tipsport League` = sport_league) %>%
  as.data.frame()
```

```{r Results Teams, eval = T, include = F, comment = F, echo = F}
result_teams <- 
  
  # - get current teams from DB
  v_match_stats %>%
  
  #filter(league %in% unique(t_mapping_league$results_league)) %>%
  
  # - assign tipsport league
  dplyr::left_join(., t_mapping_league, by = c("league" = "results_league")) %>%
  dplyr::rename(`Results League` = league,
                `Tipsport League` = tipsport_league) %>%
  dplyr::distinct() %>%
  as.data.frame() %>%
  
  # - assign current team name status from DB
  dplyr::left_join(., t_mapping_team, 
                   by = c("Results League" = "results_league", 
                          "team" = "results_team", 
                          "Tipsport League" = "tipsport_league")) %>%
  dplyr::rename(`Tipsport Team [DB]` = tipsport_team) %>%
  distinct() %>%
  as.data.frame() %>%
  
  dplyr::rename(`Results Team Name` = team) %>%
  dplyr::select(`Results League`, `Tipsport League`, 
                `Results Team Name`, `Tipsport Team [DB]`) %>%
  dplyr::rename(`Tipsport Team Name` = `Tipsport Team [DB]`) %>%
  as.data.frame() %>%
  distinct() %>%
  as.data.frame()
```

Row {data-height=700}
-----------------------------------------------------------------------

```{r Establish Team Editing, eval = T, include = T, comment = F, echo = F}
t_modDtUi <- function(id){
  ns = NS(id)
  DT::dataTableOutput(ns('x2'))
}

t_modDt <-  function(input, output, session, data){
  output$x2 <- 
    DT::renderDataTable(data, 
                        selection = "none", 
                        editable = list(target = "all",
                                        disable = 
                                          list(columns = 
                                                 c(1,2,3))), 
                        server = TRUE, 
                        options = list(scrollY = "400px", 
                                       paging = T,
                                       pageLength = 5,
                                       scrollX = TRUE, 
                                       searchHighlight = F,
                                       fixedColumns = list(leftColumns = 2)), 
                        filter = "top", class = "cell-border stripe") 
  proxy <- dataTableProxy("x2", session = session)
  
  updatedData <- eventReactive(input$x2_cell_edit, {
    info = input$x2_cell_edit
    if (!is.null(info)) {
      str(info)
      data <<- DT::editData(data, info)
    }
    data
  }, ignoreNULL = FALSE)
  
  return(updatedData)
}
```

### Joined Table
```{r Editable Team Names, eval = T, include = T, comment = F, echo = F}
t_modDtUi("editable")
changed_team <- callModule(t_modDt, "editable", data = result_teams)

# ----- Save Changes -----
saved_team_changes <- reactive({
  upload_team <- changed_team() %>% as.data.frame()
  return(upload_team)
})

# ----- Save to Database -----
actionButton("upload_team_data", h4("Store Team Mapping"))
upload_team_changes <- eventReactive(input$upload_team_data, {
  
  team_mapping <- 
    saved_team_changes() %>% 
    dplyr::select(`Results League`, `Tipsport League`, `Results Team Name`, `Tipsport Team Name`) %>%
    distinct() %>%
    dplyr::mutate(created_at = Sys.time()) %>%
    dplyr::rename(results_league = `Results League`, 
                  tipsport_league = `Tipsport League`, 
                  results_team = `Results Team Name`, 
                  tipsport_team = `Tipsport Team Name`) %>%
    dplyr::filter(!(is.na(tipsport_team)) & tipsport_team != "") %>%
    dplyr::distinct() %>%
    as.data.frame()
  
  if(nrow(team_mapping) > 0) {
    
    betting_ds$writeTable(df = team_mapping, 
                          table_name = "t_mapping_team", 
                          is_append = T, is_overwrite = F)
    
  }
})

renderText({
  upload_team_changes()
})
```

### Tipsport Teams
```{r Tipsport Helper Table, eval = T, include = T, comment = F, echo = F}
DT::datatable(tipsport_teams %>%
                as.data.frame(), 
              
              options = list(scrollY = "400px", 
                             paging = TRUE,
                             pageLength = 5,
                             scrollX = TRUE, 
                             searchHighlight = F,
                             fixedColumns = list(leftColumns = 2)), 
              filter = "top", class = "cell-border stripe")
```