---
title: "5 upcoming matches"
author: "Ing. Peter Tomko, M.A."
date: "1/9/2020"
output:
  pdf_document: default
  html_document: default
subtitle: Create list of upcoming matches
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Establish Connection
```{r connection, warning = F, message = F, error = F}
con <- DBI::dbConnect(odbc::odbc(), "betting_ds", bigint = "integer")
```

### Create view `v_upcoming_matches`
```{sql connection = con, connection = con, warning = F, message = F, error = T}
drop view if exists v_upcoming_matches;
create view v_upcoming_matches as (
select distinct dateclosed, fullname, sport_league, 
split_part(competition_name, '-', 1) t_home_team,
split_part(competition_name, '-', 2) t_away_team, rate
from t_tipsport_bookmaker
where sport = 'Fotbal'
and sport_category like '%mu%'
and type in ('u', 'o') 
and eventtype = '-91' 
and gamepart = '1/1'
and fullname not like '%(%'
and sport_league in (select distinct tipsport_league from t_mapping_league)
and dateclosed > now());
```
